name: bictov
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.3.1
  cloudinary_public: ^0.23.1
  file_picker: ^8.0.7
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_slidable: ^3.1.1
  dotted_border: ^2.1.0
  socket_io_client: ^2.0.3+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: "assets/images/bictov_splash_screen/bictovSplashScreen.png"
  android: true
  ios: true
  web: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/on_boarding_screen/
    - assets/images/register_and_auth_user_screens/
    - assets/images/
    - assets/images/ads_temporary/
    - assets/images/business_cover_photo/
    - assets/images/profile_pics/
    - assets/images/emoji_pics/
    - assets/images/products_logos/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Minion
      fonts:
        - asset: assets/fonts/app_fonts/MINIONVARIABLECONCEPT-ROMAN.OTF
    - family: Concept
      fonts:
        - asset: assets/fonts/app_fonts/Concept Medium.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/app_fonts/Tajawal-Regular.ttf
    - family: Notifications
      fonts:
        - asset: assets/fonts/icons_fonts/Notifications.ttf
    - family: EyeIconHidePassword
      fonts:
        - asset: assets/fonts/icons_fonts/EyeIconHidePassword.ttf
    - family: EyeIconShowPassword
      fonts:
        - asset: assets/fonts/icons_fonts/EyeIconShowPassword.ttf
    - family: ProfileIcon
      fonts:
        - asset: assets/fonts/icons_fonts/ProfileIcon.ttf
    - family: ChatIcon
      fonts:
        - asset: assets/fonts/icons_fonts/ChatIcon.ttf
    - family: CartIcon
      fonts:
        - asset: assets/fonts/icons_fonts/CartIcon.ttf
    - family: HomeIcon
      fonts:
        - asset: assets/fonts/icons_fonts/HomeIcon.ttf
    - family: BusinessesIcon
      fonts:
        - asset: assets/fonts/icons_fonts/BusinessesIcon.ttf
    - family: EditProfileIcon
      fonts:
        - asset: assets/fonts/icons_fonts/EditProfileIcon.ttf
    - family: MyOrdersIcon
      fonts:
        - asset: assets/fonts/icons_fonts/MyOrdersIcon.ttf
    - family: MapIcon
      fonts:
        - asset: assets/fonts/icons_fonts/MapIcon.ttf
    - family: Favorites
      fonts:
        - asset: assets/fonts/icons_fonts/Favorites.ttf
    - family: WhoWeAreIcon
      fonts:
        - asset: assets/fonts/icons_fonts/WhoWeAreIcon.ttf
    - family: ShareAppIcon
      fonts:
        - asset: assets/fonts/icons_fonts/ShareAppIcon.ttf
    - family: FacebookLogoIcon
      fonts:
        - asset: assets/fonts/icons_fonts/FacebookLogoIcon.ttf
    - family: InstagramLogoIcon
      fonts:
        - asset: assets/fonts/icons_fonts/InstagramLogoIcon.ttf
    - family: SignOutIcon
      fonts:
        - asset: assets/fonts/icons_fonts/SignOutIcon.ttf
    - family: ProductsIcon
      fonts:
        - asset: assets/fonts/icons_fonts/ProductsIcon.ttf
    - family: AddProductsIcon
      fonts:
        - asset: assets/fonts/icons_fonts/AddProductsIcon.ttf
    - family: SearchIcon
      fonts:
        - asset: assets/fonts/icons_fonts/SearchIcon.ttf
    - family: RatingBarStar
      fonts:
        - asset: assets/fonts/icons_fonts/RatingBarStar.ttf
    - family: UnfollowBusiness
      fonts:
        - asset: assets/fonts/icons_fonts/UnfollowBusiness.ttf
    - family: ProductsCount
      fonts:
        - asset: assets/fonts/icons_fonts/ProductsCount.ttf
    - family: OutlinedRatingStar
      fonts:
        - asset: assets/fonts/icons_fonts/OutlinedRatingStar.ttf
    - family: FullRoundedRatingStar
      fonts:
        - asset: assets/fonts/icons_fonts/FullRoundedRatingStar.ttf
    - family: HalfRoundedRatingStar
      fonts:
        - asset: assets/fonts/icons_fonts/HalfRoundedRatingStar.ttf
    - family: ILSIcon
      fonts:
        - asset: assets/fonts/icons_fonts/ILSIcon.ttf
    - family: UploadProductImage
      fonts:
        - asset: assets/fonts/icons_fonts/UploadProductImage.ttf
    - family: PreviewProductIcon
      fonts:
        - asset: assets/fonts/icons_fonts/PreviewProductIcon.ttf
    - family: FilterIcon
      fonts:
        - asset: assets/fonts/icons_fonts/FilterIcon.ttf
    - family: PrintInvoice
      fonts:
        - asset: assets/fonts/icons_fonts/PrintInvoice.ttf
    - family: EditProductIcon
      fonts:
        - asset: assets/fonts/icons_fonts/EditProductIcon.ttf
    - family: DeleteProductForever
      fonts:
        - asset: assets/fonts/icons_fonts/DeleteProductForever.ttf
    - family: CropProductPic
      fonts:
        - asset: assets/fonts/icons_fonts/CropProductPic.ttf
    - family: BusinessSettings
      fonts:
        - asset: assets/fonts/icons_fonts/BusinessSettings.ttf
    - family: ContactUs
      fonts:
        - asset: assets/fonts/icons_fonts/ContactUs.ttf
    - family: EditsIcon
      fonts:
        - asset: assets/fonts/icons_fonts/EditsIcon.ttf
    - family: WatsappIcon
      fonts:
        - asset: assets/fonts/icons_fonts/WatsappIcon.ttf
    - family: PhoneNumberIcon
      fonts:
        - asset: assets/fonts/icons_fonts/PhoneNumberIcon.ttf
    - family: OrderPaymentIcon
      fonts:
        - asset: assets/fonts/icons_fonts/OrderPaymentIcon.ttf
    - family: OrderDataIcon
      fonts:
        - asset: assets/fonts/icons_fonts/OrderDataIcon.ttf
    - family: FavoriteProduct
      fonts:
        - asset: assets/fonts/icons_fonts/FavoriteProduct.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
