/// Flutter icons BusinessSettings
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BusinessSettings
///      fonts:
///       - asset: fonts/BusinessSettings.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BusinessSettings {
  BusinessSettings._();

  static const _kFontFam = 'BusinessSettings';
  static const String? _kFontPkg = null;

  static const IconData business_settings = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);


  // added from add_products_icon_icons.dart file
  static const IconData cancel_circled_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_products = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_squared_alt = IconData(0xf196, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_added = IconData(0xf361, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
