/// Flutter icons ContactUs
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ContactUs
///      fonts:
///       - asset: fonts/ContactUs.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ContactUs {
  ContactUs._();

  static const _kFontFam = 'ContactUs';
  static const String? _kFontPkg = null;

  static const IconData contact_us = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
