/// Flutter icons CropProductPic
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CropProductPic
///      fonts:
///       - asset: fonts/CropProductPic.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CropProductPic {
  CropProductPic._();

  static const _kFontFam = 'CropProductPic';
  static const String? _kFontPkg = null;

  static const IconData crop_product_pic = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
