/// Flutter icons DeleteProductForever
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeleteProductForever
///      fonts:
///       - asset: fonts/DeleteProductForever.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DeleteProductForever {
  DeleteProductForever._();

  static const _kFontFam = 'DeleteProductForever';
  static const String? _kFontPkg = null;

  static const IconData delete_forever = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
