/// Flutter icons EditsIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EditsIcon
///      fonts:
///       - asset: fonts/EditsIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EditsIcon {
  EditsIcon._();

  static const _kFontFam = 'EditsIcon';
  static const String? _kFontPkg = null;

  static const IconData edits_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
