/// Flutter icons Favorites
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Favorites
///      fonts:
///       - asset: fonts/Favorites.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Favorites {
  Favorites._();

  static const _kFontFam = 'Favorites';
  static const String? _kFontPkg = null;

  static const IconData bookmark_border = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unFavoriteProduct = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoriteProduct = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
