/// Flutter icons FavoriteProduct
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FavoriteProduct
///      fonts:
///       - asset: fonts/FavoriteProduct.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FavoriteProduct {
  FavoriteProduct._();

  static const _kFontFam = 'FavoriteProduct';
  static const String? _kFontPkg = null;

  static const IconData favorite_product = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
