/// Flutter icons Notifications
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Notifications
///      fonts:
///       - asset: fonts/Notifications.ttf

import 'package:flutter/widgets.dart';

class Notifications {

  Notifications._();
  static const _kFontFam = 'Notifications';
  static const String? _kFontPkg = null;
  static const IconData notifications = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
