/// Flutter icons OrderDataIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OrderDataIcon
///      fonts:
///       - asset: fonts/OrderDataIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OrderDataIcon {
  OrderDataIcon._();

  static const _kFontFam = 'OrderDataIcon';
  static const String? _kFontPkg = null;

  static const IconData complete_order_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
