/// Flutter icons OrderPaymentIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OrderPaymentIcon
///      fonts:
///       - asset: fonts/OrderPaymentIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OrderPaymentIcon {
  OrderPaymentIcon._();

  static const _kFontFam = 'OrderPaymentIcon';
  static const String? _kFontPkg = null;

  static const IconData order_payment_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
