/// Flutter icons ProductsIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProductsIcon
///      fonts:
///       - asset: fonts/ProductsIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProductsIcon {
  ProductsIcon._();

  static const _kFontFam = 'ProductsIcon';
  static const String? _kFontPkg = null;

  static const IconData products = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
