/// Flutter icons UploadProductImage
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UploadProductImage
///      fonts:
///       - asset: fonts/UploadProductImage.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UploadProductImage {
  UploadProductImage._();

  static const _kFontFam = 'UploadProductImage';
  static const String? _kFontPkg = null;

  static const IconData UploadProdutImage = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
